mysql -u root -h localhost -p
 #Gabrielle Carvalho Gonçalves das Neves

CREATE DATABASE Locadora;
USE Locadora;

CREATE TABLE Clientes(
	NomeCliente VARCHAR(50) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	Telefone VARCHAR(11) NOT NULL
);

CREATE TABLE Alugueis(
	IdCliente INT NOT NULL PRIMARY KEY,
	Data DATETIME NOT NULL
);

CREATE TABLE Filmes(
 	IdFilme INT NOT NULL PRIMARY KEY,
 	Idade TINYINT NOT NULL
);

CREATE TABLE ItensAlugados(
	Comprovante INT NOT NULL PRIMARY KEY,
 	IdFilme INT NOT NULL,  	
	CONSTRAINT Fk_IdFilme FOREIGN KEY (IdFilme)
	REFERENCES Filmes(IdFilme)
);


#COMANDOS DE ALTERAÇÃO
ALTER TABLE Clientes
ADD COLUMN IdCliente INT NOT NULL PRIMARY KEY FIRST,
ADD COLUMN ENDERECO VARCHAR(150) NOT NULL AFTER NomeCliente,
ADD CONSTRAINT Uk_CPF UNIQUE KEY,
CHANGE COLUMN ENDERECO Endereco VARCHAR(150) NOT NULL AFTER NomeCliente;


ALTER TABLE Alugueis
DROP COLUMN IdCliente;

ALTER TABLE Alugueis
ADD COLUMN Comprovante INT NOT NULL PRIMARY KEY FIRST,
ADD COLUMN Devolucao DATETIME NOT NULL,
ADD COLUMN IdCliente INT NOT NULL,
ADD CONSTRAINT Fk_IdCliente FOREIGN KEY (IdCliente)
REFERENCES Clientes (IdCliente);


ALTER TABLE FilmeS
DROP COLUMN Idade,
ADD COLUMN Titulo VARCHAR(50) NOT NULL,
ADD COLUMN Genero VARCHAR(30) NOT NULL,
ADD COLUMN Idioma VARCHAR(20) NOT NULL,
ADD COLUMN Preco DECIMAL(5,2) NOT NULL;


ALTER TABLE ItensAlugados
DROP COLUMN Comprovante;

ALTER TABLE ItensAlugados
ADD COLUMN Comprovante INT NOT NULL,
ADD COLUMN QtdeEstoque TINYINT NOT NULL,
ADD CONSTRAINT PK_Chaves PRIMARY KEY (IdFilme, Comprovante),
ADD CONSTRAINT Fk_Comprovante FOREIGN KEY (Comprovante)
REFERENCES Alugueis (Comprovante);






